ci:
  autofix_commit_msg: '[pre-commit.ci] auto fixes'
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-json
    exclude: "\\.vscode/.*.json"
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
  - id: ruff
    args: ["--fix"]
  - id: ruff-format
